### PR TITLE
I tried to get the correct package manager

### PR DESCRIPTION
**Pull request by JoaoAlexNunes**
I tried to follow the logic on how to get the syntax preference to get the correct node packager manager #58

### CODE REVIEW

**Comment by JoaoAlexNunes** [comment]
when you can please check this

**Comment by dmmulroy** [comment]
This isn't quite right - 

The code that manages the `README` templates is this:

`src/core/readme.ml`

```ocaml
type t = Configuration.t

let template (configuration : Configuration.t) : t Template.t =
  let template_directory = Node.Path.join [| configuration.directory; "./" |] in
  Template.make ~name:"README.md.tmpl" ~value:configuration
    ~dir:template_directory ~to_json:Configuration.to_json
;;
```

The data that gets "injected" into the template is the json representation of `type t`, which in this case is just an alias for `Configuration.t` and `Configuration.to_json`. So in other words, the data injected into the template is our configuration record and it is serialized using the configuration module's `to_json` function.

We probably want to write a custom `to_json` for README where we don't capitalize the `node_package_manager` field during serialization:

`src/core/configuration.ml`

```ocaml
  Js.Dict.set dict "node_package_manager"
    (Js.Json.string
       (configuration.node_package_manager
      |> Nodejs.Process.npm_user_agent_to_string |> String.capitalize_ascii)); 
```
https://melange.re/v2.2.0/api/ml/melange/Js/Json/index.html#val-decodeObject
So we probably want something like this in `src/core/readme.ml`:

```ocaml
let to_json (readme : Configuration.t) = 
... code here similar to the to_json in configuration.ml, but only w/ the fields the readme needs ...
;;
```

**Comment by JoaoAlexNunes** [comment]
open Bindings

type t = Configuration.t

let to_json (readme : Configuration.t) =
  let dict = Js.Dict.empty () in
  Js.Dict.set dict "name" (Js.Json.string readme.name);
  Js.Dict.set dict "directory" (Js.Json.string readme.directory);
  Js.Dict.set dict "node_package_manager"
    (Js.Json.string
       (readme.node_package_manager |> Nodejs.Process.npm_user_agent_to_string));
  Js.Dict.set dict "syntax_preference"
    (Js.Json.string
       (Configuration.syntax_preference_to_string readme.syntax_preference));
  Js.Dict.set dict "bundler"
    (Js.Json.string
       (Bundler.to_string readme.bundler |> String.capitalize_ascii));
  (* We add a derived field to feed into our template for convenience *)
  Js.Dict.set dict "is_webpack_app"
    (Js.Json.boolean (readme.bundler == Webpack));
  Js.Json.object_ dict
;;

let template (configuration : Configuration.t) : t Template.t =
  let template_directory = Node.Path.join [| configuration.directory; "./" |] in
  Template.make ~name:"README.md.tmpl" ~value:configuration
    ~dir:template_directory ~to_json
;;

**Comment by JoaoAlexNunes** [comment]
I have the function like that

**Review by dmmulroy — APPROVED** [review]
lgtm - thanks!

**Pull request merged**
